import 'package:get/get_navigation/src/root/internacionalization.dart';

class Language extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'google_text': 'Google',
      'facebook_text': 'Facebook',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'enter_code': 'Please enter the Following details.',
      'username': 'Username',
      'email': 'Email',
      'return_mail': 'Please enter email',
      'return_username': 'Please enter Username',
      'return_password': 'Please enter Password',
      'return_confirm_password': 'Please enter confirm Password',
      'password': 'Password',
      'login': 'Log In',
      'otp': 'Enter OTP Code',
      'number': 'Phone Number',
      'return_number': 'Please enter Number',
      'sign_in_statement': 'Enter your username and password to get started.',
      'forgot_password': 'Forgot Password?',
      'dont_have': 'Don’t have account?',
      'otp_code': 'Enter OTP Code',
      'otp_sent_to': 'OTP code has been sent to \n (+91) 6377824837.',
      'or': 'Or',
      'verify': 'Verify',
      'explore_services': 'Explore services near you',
      'earn_1000': 'Earn 1000 for every friend you refer',
      'get_a': 'Get a friend to start using Canwinn',
    },
    'hi_IN': {
      'google_text': 'गूगल',
      'facebook_text': 'फेसबुक',
      'sign_in': 'साइन इन करें',
      'sign_up': 'साइन अप करें',
      'enter_code': 'कृपया निम्न विवरण दर्ज करें।',
      'username': 'उपयोगकर्ता नाम',
      'email': 'ईमेल',
      'return_mail': 'कृपया ईमेल दर्ज करें',
      'return_username': 'कृपया उपयोगकर्ता नाम दर्ज करें',
      'return_password': 'कृपया पासवर्ड दर्ज करें',
      'return_confirm_password': 'कृपया पुष्टि पासवर्ड दर्ज करें',
      'password': 'पासवर्ड',
      'login': 'लॉग इन करें',
      'otp': 'ओटीपी कोड दर्ज करें',
      'number': 'फ़ोन नंबर',
      'return_number': 'कृपया नंबर दर्ज करें',
      'sign_in_statement': 'प्रारंभ करने के लिए अपना उपयोगकर्ता नाम और पासवर्ड दर्ज करें।',
      'forgot_password': 'पासवर्ड भूल गए?',
      'dont_have': 'कोई खाता नहीं है?',
      'otp_code': 'ओटीपी कोड दर्ज करें',
      'otp_sent_to': 'ओटीपी कोड भेजा गया है \n (+91) 6377824837 पर।',
      'or': 'या',
      'verify': 'सत्यापित करें',
      'explore_services': 'अपने पास की सेवाओं को खोजें',
      'earn_1000': 'हर मित्र को रेफर करने पर ₹1000 कमाएं',
      'get_a': 'मित्र को Canwinn उपयोग करने के लिए प्रेरित करें',
    },
  };
}
