import 'package:flutter/material.dart';
String Account="assets/images/account_circle.png";
String Canwinn="assets/images/canwinn_logo.png";
String encryptedIcon="assets/images/encrypted.png";
String Facebook="assets/images/Facebook-logo 1.png";
String Google="assets/images/Google_Icons-09-512 1.png";
String mailIcon="assets/images/mail.png";
String visibilityIcon="assets/images/visibility_off.png";
String Backbutton="assets/images/arrow-left-01.png";
String Labtest="assets/images/11497105 1.png";
String Joinus="assets/images/5364324 (1) 1.png";
String hospitalNearme="assets/images/5005356 5.png";
String commonService="assets/images/5124557 (1) 1.png";
String Educationcentre="assets/images/6384631 (1) 1.png";
String refer="assets/images/6922144 (1) 1.png";
String appliancerepair="assets/images/Handymen repairing clients home appliance 1.png";
String doctorAppointment="assets/images/5109263 4.png";
String general="assets/images/shops 1.png";
String location="assets/images/pin 1.png";
String beautyandwellness="assets/images/salon 1.png";
String dinner="assets/images/dinner 1.png";
String canwinnconnect="assets/images/canwinn_connect.png";
String offers="assets/images/shoppingmode.png";
String services="assets/images/clinical_notes (1).png";
String home="assets/images/home_and_garden.png";
String search="assets/images/search.png";
String dropdownbutton="assets/images/keyboard_arrow_down.png";
String Notifications="assets/images/notifications.png";
String Forwardsign="assets/images/chevron_forward.png";
String ambulance="assets/images/ambulance 1.png";
String Doctor="assets/images/doctor 1.png";
String Cute="assets/images/cute 1.png";
String Floss="assets/images/floss 1.png";
String Woman="assets/images/woman 1.png";
String Phone="assets/images/phone 1.png";
String HospitalBed="assets/images/hospital-bed 1.png";
String Pharmacy="assets/images/pharmacy (2) 1.png";
const String ProfilePhoto="assets/images/healthcare-workers-preventing-virus-quarantine-campaign-concept-cheerful-friendly-asian-female-physician-doctor-with-clipboard-daily-checkup-standing-white-background 2.png";
const String Siren="assets/images/siren 1.png";
const HospitalImage="assets/images/Depth 4, Frame 1.png";
const InteriorImage="assets/images/interior-view-operating-room 1.png";
const DiscountApplicance="assets/images/8598084 1.png";
const PickserviceFirst="assets/images/3556952 1.png";
const HospitalDetailImage="assets/images/Tiny doctors and patients near hospital flat vector illustration 1.png";
const Offercleaning="assets/images/Depth 4, Frame 1.png";
const Homecleaning="assets/images/Depth 5, Frame 0.png";
const wellnessHealthLettring="assets/images/wellness-health-lettering-chalkboard 1.png";
const WallPhoto="assets/images/WallPhoto.png";
const LimitedTime="assets/images/LimitedTime.png";
const FreeHomeConsultant="assets/images/freehomeConsultant.png";




